name: Quick Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run basic tests
        run: |
          python test_analyzer.py

      - name: Test analyzer functionality
        run: |
          python analyzer.py logs/auth.log --quiet
          echo "✅ Basic functionality test passed"
